baseurl = "https://kamek.pages.dev"
title = "DevOps with love"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "kamek437"
enableGitInfo = true

[params]
author = "Kamek"
info = ["Full Stack DevOps and Magician"]
description = "Kirill Kazakov's personal page"
keywords = "blog,businesscard,personal,devops,kksudo,kirill,kazakov"
gravatar = "kamek437@gmail.com"

since = 2010
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/kamek437/kamek/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/kamek437/"
target = "_blank"
[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/kamek437"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/kamek437"
target = "_blank"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/kamek437/"
target = "_blank"
[[params.social]]
name = "kamek437@gmail.com"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:kamek437@gmail.com"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"


